### ISSUE TITLE
Hooks is not a module (Redmine 2.6)

### ISSUE THREAD

**Issue by jonnsn** [jrupesh/redmine_my_page#12]
Hi,

when I'm trying to install the plugin in a redmine 2.6 installation I get the following error on executing
`bundle exec rake redmine:plugins:migrate RAILS_ENV=production`

> rake aborted!
> Hooks is not a module
> redmine/plugins/redmine_my_page/lib/hooks/redmine_my_page_hook.rb:1:in `<top (required)>'

is there any dependency missing?
Redmine 2.6
Ruby 2.0.0
Rails 3.2.22

Thanks for your suggestions.

**Comment by MichaelZahar** [comment]
same (

Environment:
  Redmine version                3.0.3.stable.14369
  Ruby version                   2.0.0-p643 (2015-02-25) [x86_64-linux]
  Rails version                  4.2.2
  Environment                    production
  Database adapter               Mysql2
SCM:
  Subversion                     1.8.8
  Mercurial                      2.8.2
  Git                            1.9.1
  Filesystem  
Redmine plugins:
  redmine_checklists             3.1.3
  redmine_custom_css             0.1.6
  redmine_custom_js              0.1.0
  redmine_dashboard              2.7.0
  redmine_people                 1.1.1
  redmine_subtasks_inherited_fields 1.1.0
  redmine_theme_changer          0.2.0
  redmine_zenedit                0.0.2
  time_logger                    0.5.3
  timelog_timer                  2.0.0

**Comment by jrupesh** [comment]
Hi,

Can you let me know if the directory path is similar in your Redmine server?
<redmine install path>/plugins/redmine_my_page

And the file init.rb exists in the directory
--> <redmine install path>/plugins/redmine_my_page/init.rb

Thank You.

**Comment by jonnsn** [comment]
Thanks for your help!
Yes, I can confirm these paths and files are present and correct.

**Comment by jrupesh** [comment]
Please reopen the issue if this commit has not solved the issue.
Thank You

**Comment by jonnsn** [comment]
Thank you very much, install worked fine for me now!
