### ISSUE TITLE
My page blocks added have an English name

### ISSUE THREAD

**Issue by gc-olivierho** [jrupesh/redmine_my_page#13]
It would be nice adding translations for the names of added blocks in my page.
In order to do so, we simply need to add strings labeled after My page block names:
en:
  activities: Activity
  custom_query_issues_list: Issue lists from my queries
  my_custom_queries: My queries

in config/locales/en.yml

I can provide French and Russian files if you want.

**Comment by jrupesh** [comment]
Please provide the translation files, I can put it in my repo.
Thank you for the contribution.

**Comment by gc-olivierho** [comment]
Here they are ! Russian comes from yumash that I got when forking your repository in mid-December. I completed all 3 languages with the 3 new strings.

[locales.zip](https://github.com/jrupesh/redmine_my_page/files/110760/locales.zip)
