### ISSUE TITLE
"Select Queries" button briefly shows a loading symbol then nothing happens

### ISSUE THREAD

**Issue by kckemper** [jrupesh/redmine_my_page#14]
Using Redmine 2.4.2 and I do have custom queries setup.  The "my queries" widget seems to work OK.

**Comment by jrupesh** [comment]
Ok, Great to hear that you have this working. I close this issue.

**Comment by kckemper** [comment]
Well it the "select queries" doesn't work, just the "my queries" widget part.  This isn't an issue in redmine 3.2.0 though.
