### ISSUE TITLE
error on opening my_site

### ISSUE THREAD

**Issue by mourningsun75** [jrupesh/redmine_my_page#2]
Started GET "/my/page" for xxx.xxx.xxx.xxx at 2015-04-20 18:01:38 +0200
Processing by MyController#page as HTML
  Current user: xxx (id=3)
  Rendered my/blocks/_timelog.html.erb (676.7ms)
  Rendered plugins/redmine_my_page/app/views/my/_my_queries_issue_list.html.erb (2.8ms)
  Rendered plugins/redmine_my_page/app/views/my/blocks/_custom_query_issues_list.html.erb (3.2ms)
  Rendered my/page.html.erb within layouts/base (680.7ms)
Completed 500 Internal Server Error in 701ms

ActionView::Template::Error (undefined method `statement' for nil:NilClass):
    1: <% query = IssueQuery.find_by_id(query_id)
    2:    query_issues = Issue.joins(:status, :tracker, :project, :priority).where(
    3:     query.statement).limit(query_limit).to_a
    4:    query_issues_count = Issue.joins(:status, :tracker, :project, :priority).where(
    5:     query.statement).count
    6:    param_hash = query.project_id.nil? ? { :query_id => query_id } : { :project_id => query.project_id, :query_id => query_id }
  app/views/my/page.html.erb:11:in`block in _app_views_my_page_html_erb__469832764_105562270'
  app/views/my/page.html.erb:8:in `each'
  app/views/my/page.html.erb:8:in`_app_views_my_page_html_erb__469832764_105562270'

**Comment by jrupesh** [comment]
Thank You for morningsun75 for pointing out this.
The issue is corrected in the latest commit. (949feef0deb61898679ad30a3461c6bb51b6d786)

Please rate the plugin in redmine.org.

**Comment by mourningsun75** [comment]
Installed the new Version... next error:

Started GET "/my/page" for xx.xx.xx.xx at 2015-04-22 11:55:02 +0200
Processing by MyController#page as HTML
  Current user: xxx (id=3)
  Rendered plugins/redmine_my_page/app/views/my/blocks/_my_custom_queries.html.erb (12.4ms)
  Rendered my/page.html.erb within layouts/base (14.0ms)
Completed 500 Internal Server Error in 28ms

ActionView::Template::Error (undefined method `archived?' for nil:NilClass):
    11:       param_hash = my_query.project_id.nil? ? { :query_id => my_query.id } : { :project_id => my_query.project_id, :query_id => my_query.id } %>
    12:         <tr id="myquery-<%= index %>" class="<%= cycle('odd', 'even') %>">
    13:           <td class="id"><%= index + 1 %></td>
    14:           <td class="project"><%= link_to_project(my_query.project) %></td>
    15:           <td class="tracker"><%= link_to "#{my_query.name}", issues_path( param_hash ), :target => '_blank' %></td>
    16:         </tr>
    17:     <% end %>
  app/helpers/application_helper.rb:141:in`link_to_project'
  app/views/my/page.html.erb:11:in `block in _app_views_my_page_html_erb__346984262_100831780'
  app/views/my/page.html.erb:8:in`each'
  app/views/my/page.html.erb:8:in `_app_views_my_page_html_erb__346984262_100831780'

**Comment by jrupesh** [comment]
Thank You.
Fixed : A check has been added to Show "All Projects Query" and also the list shows only queries from active projects.

**Comment by mourningsun75** [comment]
Tested and seems to work now!

Thank you!
