### ISSUE TITLE
Redmine 3.2.1 with the plugin 500 error

### ISSUE THREAD

**Issue by archonwang** [jrupesh/redmine_my_page#20]
the log is 

> Started GET "/settings/plugin/redmine_my_page" for 192.168.60.239 at 2016-04-15 14:03:07 +0800
> Processing by SettingsController#plugin as HTML
>   Parameters: {"id"=>"redmine_my_page"}
>   Current user: admin (id=1)
>   Rendered plugins/redmine_my_page/app/views/settings/_my_page_option_settings.html.erb (10.4ms)
>   Rendered settings/plugin.html.erb within layouts/admin (25.3ms)
> Completed 500 Internal Server Error in 60ms (ActiveRecord: 2.2ms)
> 
> ActionView::Template::Error (no implicit conversion of Symbol into Integer):
>     1: <p>
>     2:   <label><%= l(:label_my_activity_enable) %></label>
>     3:   <%= check_box_tag 'settings[my_activity_enable]', 1, @settings[:my_activity_enable] == "1" %>
>     4:   <br />
>     5:   <em><%= l(:em_my_activity_enable) %></em>
>     6: </p>
>   plugins/redmine_my_page/app/views/settings/_my_page_option_settings.html.erb:3:in `[]'
>   plugins/redmine_my_page/app/views/settings/_my_page_option_settings.html.erb:3:in`_35e72d247994c46ef48a3e1e2bcd0573'
>   plugins/redmine_workflow_enhancements/lib/workflow_enhancements/patches/action_view_rendering.rb:53:in `render_with_workflow_enhancements'
>   app/views/settings/plugin.html.erb:6:in`block in _84aa70a722df0592159e77304cea73c0'
>   app/views/settings/plugin.html.erb:4:in `_84aa70a722df0592159e77304cea73c0'
>   lib/redmine/sudo_mode.rb:63:in`sudo_mode'

My environment is 
Redmine 3.2.1 Stable
when I open the plugins - configuration the error occured? any solution?
Thanks.

**Comment by archonwang** [comment]
another question
when I open the select query , the page dislpay something wrong... 
it seems not support redmine 3.2.X.

**Comment by jrupesh** [comment]
Hi,
can you please let me know the Ruby version.
Not able to figure out the cause. :(
Thanks.

**Comment by archonwang** [comment]
o , I missed it . sorry.
there is some information about the ruby and rails, hope it would help you.

> Rails version 4.2.5.2
> Ruby version  2.2.4-p230 (x86_64-linux)
> RubyGems version  2.4.5.1
> Rack version  1.6.4
> Middleware    
> 
> ```
> Rack::Sendfile
> ActionDispatch::Static
> #<ActiveSupport::Cache::Strategy::LocalCache::Middleware:0x00000005dfd180>
> Rack::Runtime
> Rack::MethodOverride
> ActionDispatch::RequestId
> Rails::Rack::Logger
> ActionDispatch::ShowExceptions
> ActionDispatch::DebugExceptions
> ActionDispatch::RemoteIp
> ActionDispatch::Callbacks
> ActiveRecord::ConnectionAdapters::ConnectionManagement
> ActiveRecord::QueryCache
> ActionDispatch::Cookies
> ActionDispatch::Session::CookieStore
> ActionDispatch::Flash
> ActionDispatch::ParamsParser
> ActionDispatch::XmlParamsParser
> Rack::Head
> Rack::ConditionalGet
> Rack::ETag
> Rack::ContentLength
> RequestStore::Middleware
> OpenIdAuthentication
> ExceptionNotification::Rack
> Rack::RawUpload
> ```
> 
> Application root  /opt/redmine
> Environment   production
> Database adapter  mysql2
> Database schema version   20151209153801

**Comment by amityk77** [comment]
Similar type of error is in 3.2.2
 Additional details of config:

Environment:
  Redmine version                3.2.2.stable
  Ruby version                   2.3.1-p112 (2016-04-26) [x86_64-linux]
  Rails version                  4.2.5.2
  Environment                    production
  Database adapter               Mysql2

**Comment by bluekite17** [comment]
+1, I got same error when disable plugin

```
Environment:
  Redmine version                3.3.0.stable
  Ruby version                   2.3.1-p112 (2016-04-26) [x86_64-linux]
  Rails version                  4.2.7.1
  Environment                    production
  Database adapter               Mysql2
SCM:
  Subversion                     1.8.8
  Filesystem                     
Redmine plugins:
  redmine_my_page                0.1.9
```

I try print settings.

```
@settings.to_yaml -> --- ''
```
