### ISSUE TITLE
Agile-Taskboard?

### ISSUE THREAD

**Issue by dmaczasek** [jrupesh/redmine_my_page#25]
Is it possible to have the Agiletaskboard as startpage?

thanks ahead

**Comment by jrupesh** [comment]
Which plugin is that?
I guess it can be supported.

**Comment by dmaczasek** [comment]
The Redmine "my page" Plugin which sets the starting page after login. I havent seen a chance to choose the Agile taskboard. Just Overview und issue Pages.

**Comment by dmaczasek** [comment]
@jrupesh 
sorry, I do not want to be annoying but its very important for me :) Do you understand my issue? Is it possible to connect you via email?

Thanks ahead.

**Comment by SkunkerAG** [comment]
This would be a benefit for me, too.

**Comment by jrupesh** [comment]
Available now.
