### ISSUE TITLE
Redmine compatable version

### ISSUE THREAD

**Issue by dinya** [jrupesh/redmine_my_page#26]
The compatability with Redmine 3.4.x, 3.3.x is announced in the changelog for the version 1.10  (http://www.redmine.org/plugins/redmine_my_page).

But in the last [README.md file](https://github.com/jrupesh/redmine_my_page/blob/e1e9b79ca18fb621ec97f855f7d0a291c738bdcf/README.md) is written:

> Tested as compatible with Redmine v3.0.1

Is the README.md information is old? Or is the typo is in the changelog?

**Comment by jrupesh** [comment]
Hi, 
Yes it is compatible with 3.4.x and 3.3.x, We use the latest 3.3.1 in our org. 
Sorry for missing the update in the Readme.md I will update it soon.
Thanks.

**Comment by dinya** [comment]
Thanks
