### ISSUE TITLE
cant open activities

### ISSUE THREAD

**Issue by mourningsun75** [jrupesh/redmine_my_page#3]
Started GET "/projects/emacs/issues/new" for xxx at 2015-04-24 10:05:31 +0200
Processing by IssuesController#new as HTML
  Parameters: {"project_id"=>"emacs"}
  Current user: xxx (id=3)
  Rendered issues/_form_custom_fields.html.erb (8.7ms)
  Rendered issues/_attributes.html.erb (30.4ms)
  Rendered issues/_form.html.erb (58.2ms)
  Rendered attachments/_form.html.erb (3.8ms)
  Rendered issues/new.html.erb within layouts/base (104.2ms)
Completed 200 OK in 182ms (Views: 150.9ms | ActiveRecord: 10.1ms)
Started GET "/projects/emacs/activity" for 78.94.133.209 at 2015-04-24 10:05:33 +0200
Processing by ActivitiesController#index as HTML
  Parameters: {"id"=>"emacs"}
  Current user: mourningsun75 (id=3)
  Rendered plugins/redmine_my_page/app/views/activities/index.html.erb within layouts/base (32.7ms)
Completed 500 Internal Server Error in 84ms

**Comment by jrupesh** [comment]
Hi,

Not sure of this issue,
Can you try.

In the Administration ~ Plugins ~ "My Page Customization" configure ~ And Un-check and Save.
And let me know if this issue happens ?

**Comment by mourningsun75** [comment]
Hi,

issue stays the same...

**Comment by BRUTEF0RCE** [comment]
I do have the same issue...

**Comment by jrupesh** [comment]
Hi,
Can you please check with the latest commit.
I have refractored some code. I hope this resolves the issue.
Thanks.

**Comment by BRUTEF0RCE** [comment]
I confirm that this latest commit as of now is behaving properly on the activity tab of projects which was not the case before that for me.  Thank you M. Rupesh for this great plugin! :) I will keep you informed if I find anything else not working properly.

**Comment by jrupesh** [comment]
Thank you.
Can you please confirm that even when we check the plug-in settings this
feature works?

**Comment by BRUTEF0RCE** [comment]
I confirm that I have the "Enable Activity listing in MyPage...Check this to enable Activity page listing in the users My Page. Some bugs persist in the core Redmine activity fetcher." checkbox checked and it seems to work fine!

**Comment by jrupesh** [comment]
Thank you BRUTEF0RCE ....

Thanks a lot for your feedback.
Please rate my plugin on Redmine.org.

**Comment by BRUTEF0RCE** [comment]
already done! :)
