### ISSUE TITLE
Enable Activity listing status is always unchecked on reopened/refreshed configuration page.

### ISSUE THREAD

**Issue by urkon** [jrupesh/redmine_my_page#32]
Environment:
Redmine version 3.4.2.stable
Ruby version 2.4.2-p198 (2017-09-14) [x86_64-linux]
Rails version 4.2.8
Environment production
Database adapter PostgreSQL

Redmine plugins:
redmine_my_page 0.1.10
....

When 'Enable Activity listing in MyPage.' status is checked it breaks activity log as it is written in the note.
But when the configuration page is reopen/refreshed, status is unselected.

To deselect user must select it and deselect to get activity log work again.
I am expecting to see the actual status the first time.

No logs are found.

**Comment by jrupesh** [comment]
Fixed,
Please wait for the new version.
Thanks
