### ISSUE TITLE
404 error

### ISSUE THREAD

**Issue by TheArtistCoder** [jrupesh/redmine_my_page#4]
hi,
I just tried your plugin on my v3 environment but I am getting a 404 on the admin page??

 Redmine version                3.0.1.stable
  Ruby version                   2.2.1-p85 (2015-02-26) [x86_64-linux]
  Rails version                  4.2.0

I simply used the zip download tonight
thanks for your help

**Comment by jrupesh** [comment]
Hi, 
Can you just brief where exactly in the admin page ?
Can you also paste the log of the error.

Thank You

**Comment by alancement** [comment]
Hi, 

I install the widget with a git clone 
I've some 404 pages too. It happens when I choose in the dropdown of my page different choices. After that, all the page "my page" is in 404
![redmine](https://cloud.githubusercontent.com/assets/8836911/7373288/c8b21354-edcb-11e4-8f14-cb2065553aba.jpg)

My environment is : 
Redmine version 3.0.1.stable
Ruby version 1.9.3
Linux : Debian7

Thanks for the help

**Comment by jrupesh** [comment]
Hi,
Sorry this is of not much help for me.
In your server, in the redmine directory, Can you share the information in the log/production.log file.

<redminePath>/log/production.log

This would give me information with which hopefully I can resolve this issue asap.

Thanks.
Regards,
Rupesh

**Comment by TheArtistCoder** [comment]
Hi,
here is the log:
`Started GET "/admin/plugins" for 10.216.0.248 at 2015-05-03 23:03:51 -0400
Processing by AdminController#plugins as HTML
  Current user: admin (id=1)
  Rendered admin/plugins.html.erb within layouts/admin (8.3ms)
  Rendered admin/_menu.html.erb (10.2ms)
  Rendered layouts/base.html.erb (27.5ms)
Completed 200 OK in 81ms (Views: 68.8ms | ActiveRecord: 1.9ms)
Started GET "/settings/plugin/redmine_my_page" for 10.216.0.248 at 2015-05-03 23:03:54 -0400
Processing by SettingsController#plugin as HTML
  Parameters: {"id"=>"redmine_my_page"}
  Current user: admin (id=1)
  Rendered settings/plugin.html.erb within layouts/admin (9.1ms)
Missing template, responding with 404
  Rendered common/error.html.erb within layouts/base (2.2ms)
Completed 404 Not Found in 177ms (Views: 60.3ms | ActiveRecord: 29.9ms)`

to install the plugin, I have just unzipped the file under the plugin directory, chown to www-data and restarted apache
thanks

**Comment by TheArtistCoder** [comment]
Hi,
I just fixed the problem: the issue was really simple: I used the download link from github and unzipped the file under the plugin directory. The problem is that the directory had to be renamed because it had "_master" in the name...

**Comment by jrupesh** [comment]
Great to hear that the issue was solved. :)
Closing the issue.

**Comment by alancement** [comment]
Hello, 

It's not completly resolved, I've got stille the 404 page. Indeed, We change before you said the name of the directory. 
When I check the log, I've got : 

Started GET "/my/page" for 172.16.109.9 at 2015-05-04 11:58:46 +0200
Processing by MyController#page as HTML
  Current user: admin (id=1)
  Rendered my/page.html.erb within layouts/base (37.2ms)
Missing template, responding with 404
  Rendered common/error.html.erb within layouts/base (0.7ms)
  Rendered plugins/redmine_wiki_extensions/app/views/wiki_extensions/_html_header.html.erb (0.9ms)
  Rendered plugins/redmine_wiki_extensions/app/views/wiki_extensions/_body_bottom.html.erb (0.8ms)
Completed 404 Not Found in 230ms (Views: 29.6ms | ActiveRecord: 5.1ms)

**Comment by jrupesh** [comment]
Hi, After changing the directory, Your directory structure should be something like below,
<redmineinstall>/plugins/redmine_my_page

And in the directory, Can you update the latest files from this repository.
Restart the server and this should solve the issue ?
Let me know if this solved the issue.!!
