### ISSUE TITLE
Not compatible with Redmine 4.1

### ISSUE THREAD

**Issue by sphereweb83** [jrupesh/redmine_my_page#45]
Will you be able to make this plugin compatible with Redmine 4.0 or 4.1?

**Comment by kosckosc** [comment]
Hi
I have error in redmine 4.2.1 and only when you choose "Activity" tab
here is error from log:


```
Started GET "/projects/hostin/activity" for 192.168.0.24 at 2021-07-26 09:04:20 +0200
Processing by ActivitiesController#index as HTML
  Parameters: {"id"=>"MyProject"}
  Current user: my.email@test.com (id=16)
Completed 500 Internal Server Error in 211ms (ActiveRecord: 6.4ms)

NameError (undefined local variable or method `index_without_esi' for #<ActivitiesController:0x00007f3434cd5400>
Did you mean?  index_with_esi):

plugins/redmine_my_page/lib/my_page_patches/activities_controller_patch.rb:87:in `index_with_esi'
lib/redmine/sudo_mode.rb:61:in `sudo_mode'
Creating scope :system. Overwriting existing method Enumeration.system.
```

**Comment by sanak** [comment]
@jrupesh (CC: @smeagol74, @hlubek)
I think that the following fix is missing in #46.
- https://github.com/networkteam/redmine_my_page/commit/f34e14455bd0f03fa0775d43a5868b73cbe74e64

Is it better for me to create PR from above commit ?

**Comment by smeagol74** [comment]
> Is it better for me to create PR from above commit ?

Oops... I'm too newbie in RoR :) Thank you. 

As far as my PR is already merged you just may open new PR from the current master

**Comment by smeagol74** [comment]
And @sanak , I believe that your patch will fix the #47 also

**Comment by sanak** [comment]
@smeagol74 (CC: @jrupesh, @hlubek)
Okay, no problem and thanks for confirmation.
I will create a new PR from master.

**Comment by luizjr** [comment]
Hi, @jrupesh will this plugin support version 5 of Redmine?

**Comment by sanak** [comment]
Hi @jrupesh, @luizjr  
We recently supported Redmine 5.0 on our gtt-project fork's PR (https://github.com/gtt-project/redmine_my_page/pull/13).

I will create the same PR to here in a week.

**Comment by luizjr** [comment]
@sanak Man, how wonderful!
Thanks for the quick response, I hope the Merge request is as quick as your response.

I'm looking forward to it! Thanks!

I also hope that once requested it will be merged quickly by @jrupesh .

**Comment by sanak** [comment]
@jrupesh (CC: @luizjr)
I know I'm a week late, but I created the PR #49, so checking/reviewing it is helpful.
Thanks!
