### ISSUE TITLE
how to select the default homepage?

### ISSUE THREAD

**Issue by TheArtistCoder** [jrupesh/redmine_my_page#5]
hi,
per your documentation: "the plugin also provides the default page to be shown after login into the system. This can be the My Page or any Projects Issue List or Filtered Issue List."
Where can this setting be found? this is a great feature!
thanks in advance for your help
G

**Comment by jrupesh** [comment]
Hi,

The default page can be set in the User's My Account page.
There is a option to select the page to be shown after login. ( In the preferences section )

Thanks.

PS: Please rate the plugin in Redmine.org if you find this plugin useful.
