### ISSUE TITLE
The activity listing does not seem to list all selected listing item like "spent time", "changesets", ...

### ISSUE THREAD

**Issue by BRUTEF0RCE** [jrupesh/redmine_my_page#6]
The activity listing seems to only list issue checkboxed items and does not seem to list all selected other possible listing items like :
 Changesets
 News
 Documents
 Files
 Wiki edits
 Messages
 Spent time

At least "spent time" and "changeset" related to filtered activity issues should be listed.  What do you think?  

And thanks a lot for this plugin!

**Comment by jrupesh** [comment]
Hi,
Well, its not in the default activity list.
Need to look at the feasibility.
Will get back on this.
Thanks.

**Comment by jrupesh** [comment]
Hello @BRUTEF0RCE 
The enhancement is now available. The TimeEntry and the Changeset of the filtered list of tickets are also visible now.
Thanks.
