### ISSUE TITLE
Sorting does not work

### ISSUE THREAD

**Issue by ghost** [jrupesh/redmine_my_page#7]
A created sorted issues query is printed unsorted in the custom queries list widget.

**Comment by jrupesh** [comment]
You mean the selected Issue Custom queries or the issues that are displayed in the table?

**Comment by ghost** [comment]
I mean the list of issues. I'd like to have them sorted by priority, in my custom query they are, but on the "My page" they are not sorted.

**Comment by jrupesh** [comment]
Thank You,

Issue corrected with the latest commit.
Please confirm the fix. :)

**Comment by ghost** [comment]
Hi, thanks for the fast fix. Unfortunately this did not work. I added some debugging output of `query.sort_criteria` and `sort_clause`:

Output of `query.sort_criteria` in line 2 is: `[["priority", "desc"]]` which is correct.

Output of both in line 15/16 is `[["priority", "asc"]]` and `["enumerations.position"]` which both lack the descending attribute.

**Comment by jrupesh** [comment]
Sorry bit lost here.
Which file did you put the debug out?

Also, the issue I noticed, 
- Whenever the filter is udpated, it is not automatically reflected in the My Page, Re-login to redmine will show the updated issue list.

**Comment by ghost** [comment]
A re-login did the trick. Although this is kind of annoying... but maybe not part of your plugin.
I changed `app/views/my/_my_queries_issue_list.html.erb`.

**Comment by jrupesh** [comment]
Yes, Re-login, I am looking at this, The session is not getting updated with the new columns..!
Right now, Not able to figure out the reason! :(

**Comment by jrupesh** [comment]
Please take the latest commit.. This should fix the issue of re-login.! And the sort issue list in My Page. :)

**Comment by ghost** [comment]
Yes, works fine now. Thanks!

**Comment by jrupesh** [comment]
Thanks.
Please rate the plugin in redmine.org.
